name: main-pipeline

on:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    if: github.actor != 'dependabot[bot]'
    uses: malurneelima/ci-workflow/.github/workflows/java-workflow.yaml@main
    secrets: inherit
    with:
      skip-codeql-step: false
